"""empty message

Revision ID: 02947d9073cb
Revises: 
Create Date: 2025-01-21 20:00:57.168305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02947d9073cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.String(length=255), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
