"""Added image_path and video_path to Recipe

Revision ID: 3b1e11ab7f98
Revises: 02947d9073cb
Create Date: 2025-03-10 17:39:56.727713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1e11ab7f98'
down_revision = '02947d9073cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('ingredients',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('video_path')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
