"""empty message

Revision ID: cf1567be911d
Revises: dd7389c3964d
Create Date: 2025-03-11 18:39:33.100937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1567be911d'
down_revision = 'dd7389c3964d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False))
        batch_op.drop_column('is_premium')
        batch_op.drop_column('steps')
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('steps', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('instructions')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
